services:
  web:
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
    environment:
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
    restart: always
