FROM node:20-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json turbo.json ./
COPY apps/web/package.json ./apps/web/
RUN mkdir -p packages
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev", "--workspace=apps/web"]
